# Build script for Travis CI
#

# use xenial distribution
dist: xenial

# no need to check for oracle's java
language: java
jdk: openjdk8


# speed up builds by caching maven local repository
# we are also using python via conda/pip
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.cache/pip"
  - "$HOME/miniconda3"

# as agreed in our SOP
branches:
  only:
  - master
  - development
  # Travis treats pushed tags as branches
  - /^[vV]?\d+\.\d+\.\d+$/ # matches e.g., v1.2.3, 1.2.3, V1.2.3

# added to make logs look cleaner, crisper, certified fresh
before_install: unset _JAVA_OPTIONS 

# dependencies for report generation (use cache to speed up builds)
install: 
  - $HOME/miniconda3/bin/conda --version || ./.install-reports-dependencies.sh

# check if we need to add a license file for Vaadin charts
before_script: if [ "$VAADIN_CHARTS_LICENSE_CODE" != "" ]; then
                  echo "$VAADIN_CHARTS_LICENSE_CODE" > ~/.vaadin.charts.developer.license;
               fi;

# as agreed in our SOP, build everything (don't deploy, just try to 'mvn package' locally, which covers unit tests)
script: mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml clean cobertura:cobertura package
# upload code coverage report, generate maven site (javadocs, documentation, static code analysis, etc.)
after_success: 
- bash <(curl -s https://codecov.io/bash)

# upload to maven
deploy:
  # as agreed in our SOP, builds on development branch will deploy to our maven repository after validating
  # the artifact has a proper SNAPSHOT version
  # make sure to skip integration tests! (using -DskipITs)
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings .travis.settings.xml deploy -DskipITs
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
  # as agreed in our SOP, releases are performed by tagging commits,
  # the version string and version of dependencies are validated (no snapshots allowed)
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles !development-build,release-build --settings .travis.settings.xml deploy -DskipITs
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true

# activate our conda environment, generate maven site and upload reports to gh-pages branch
after_deploy:   
  - echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && source ~/.bashrc && conda activate qbic-docs-build
  - mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml site 
  - ./.generate-reports.py $TRAVIS_BRANCH $TRAVIS_REPO_SLUG "[skip travis] Updated gh-pages" "This commit was performed from travis-ci.com using a personal access key" "Build ID $TRAVIS_BUILD_ID" "Job ID TRAVIS_JOB_ID" "Branch $TRAVIS_BRANCH" "Log of this build found at $TRAVIS_JOB_WEB_URL"

# credentials
env:
  global:
    - secure: "CyVKxK0LhJ/wAYz/z/Pzk08xSTq9rHRkoTUgoCCI3m4pqFa66kNzaWYqd8G/ug8/3K9P+3muclwwNFHZqi7UTS4pZzqUAEB5wmPJYbfiQVyLKj4+8v+eLNRHYfiYIH8HRZFAtvg1QNgI36s5zLzGE+YIQOLFS7T5AHlr4efADgYfHzH4nJzHESKvNhjiTkZRXzMZbBB2S2Ab+R3K3IJua/lIJ7Jtv1zwXHfTaoAbKeWF4xZW5obTbgnaFy6+qkDoblQqqwwdglQbirw/FfTtP4rFAcJcf6qTp/rNbuaLnwh65NRyL0IadF2M2oiQLNxO4Mhe5y3VR4QCmSFvpH/+MEdNkjlCNvEGOZ0VGmBp6qAvUFkJrZObFz73QHkf82r9tIrV9dd1R7ELUCQaAgVuxpuGYo0Z2H1MeRfDA6/zyr/PLiXBDO9BtFJj6SGI13eXsl86wwzuHIjEge0Si98Zal5pp2rd5Aq8oh/gnII5tD/HD+1EztEb2drlPljxSST1UZ3kjBaTPlAfSC53JKfKitlTpdulArw0tLp6l1TfoQhXGE5LuSBQ5FgZq/YbiEpm+uBFSVPVXyXR5BMHcf67cSeqCBzvfwXdfsYBS2MEzyMGbiK1ywEzd+3c0o2TNAfGVe3FE6xIJy3arYOnMt9W12glKDZYXrJ0yex7YkHu6zA="
    - secure: "OcbjosVWLoUl0Dl+Z9xxyeor7qHZs+dXdsD4A39wdbbYtrH2JbDTvQhflWjWdkBErdh4ddzJKYPfAIkXk9nbP+wO7cC/HId8BIE9XNKcydlEbWt8rgz1+EJst8we8Ybf+24JhCT/37/huNev+B+kq4JLWLnT5x6zY3KqFv8JAB/7a1AeZ18+HgmqJnao/SAkXAI0swXr337t7aiwks16NCMuJGlfLDTP2F5r0cyBKu2mA1KlKefs14yK7LOZsw4ZDB/MfcTanap3OqK/UlFC0wuw0gSlO5s8EWkRsBZakCjVpRytZYvrUwtLdLhiMukzSBEZt0pR+cC2t9CxEZm94WKyruZBL9dlenZ6XhObFGpM4Ai6mNl1HM7ox8rcEb6Vr2qikTTrajH9qLF7g3DhVf4lR+H3QbCpsxFlmd0scUQIUdKiQSCqotOoKMJWJGoylEwr5xyzuYjq9EtDuyreiq4FsUecbwwm6p4av8kq5iMIcYf63oPKyC39TYUIzgITbLPSCNYXseIFqGCrj5oAMoBXSdrZEDhT85aJz02X6P4Jc7+JNKP1HcbAaZa0XH5cE1NlzzwiRzysQYKw/OgpA6MJ0SI6oWfEKA4rvkzT7rNPzZp9vaBC/keDhLlsPp8N6mu56Hv3tRMDy5TBS9NBzx71j+W5YPAEZXWaNENE9RE="
    - secure: "EdMGG/LvHMIH8usGfbRY0BddIBu+m1nokmYEoHrNGGJ33yCjKuh9Y9BVHpwjuPAr4yaKJcHVQw2VIsbA2joKmUP/lBWnWycUpCnfmzZoHeZLz57bvFVVn2KWnwD8p7V7mhJOPksLTZ6gi4OO9qD3QQWa41JqMm+bNgxw655xFwcUIqRU8St1Tl14HmK6U+nQNnmfa9TjLtPOLOOzdINHbYDPloljHI29nroeJg7K6u2fsZ7io97g+wRIqcxce8JEHYz9+RdgzmCDSypkvSNNGItE41zl8ZLiO1yAjDXGDODrpcSf/N/ib54LgzXlSnlw/29nAfCIe3Mq0MLLHQSOwoABXN6QN5/ggcTzfPlD/ktEGeX4A253K1zWFdNEJecIdrDvf+l5S4Isp6SjPZY7AMiJBpFpBCzOfWx+rmwTpQ0XACxog8eu9afLXwhcnfkEkwDiVOJDnjSNpnDV4eO1uVeTb/r6/7s4hArhZyIyjT/5wWTdIsP9XUlQ9q4QVs9+vn3zNWQk0KkdWhsxY1F9ghwB9caOab64wHXCuW3aWaz0pO81BJN+y19lw07bHqofQbL6RPQXi5E0aFD/A+c1GOvqkO9e1sIQk0RrU0AXI4QaZFkTx2rYYHFxdsjkLwEqxOuvaM1JIB/Sps2tlvdZ0UNRqRd2582Z+PdNHCubdLs="

